/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-05-23 04:34:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class product_002ddetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("file:/C:/Users/admin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1716315550419L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/.m2/repository/org/springframework/spring-webmvc/6.1.6/spring-webmvc-6.1.6.jar!/META-INF/spring.tld", Long.valueOf(1712798146000L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/.m2/repository/org/springframework/spring-webmvc/6.1.6/spring-webmvc-6.1.6.jar!/META-INF/spring-form.tld", Long.valueOf(1712798146000L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("file:/C:/Users/admin/.m2/repository/org/springframework/spring-webmvc/6.1.6/spring-webmvc-6.1.6.jar", Long.valueOf(1716315547076L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>San pham ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetailId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--begin::Main-->\r\n");
      out.write("<div class=\"app-main flex-column flex-row-fluid\" id=\"kt_app_main\">\r\n");
      out.write("    <!--begin::Content wrapper-->\r\n");
      out.write("    <div class=\"d-flex flex-column flex-column-fluid\">\r\n");
      out.write("        <!--begin::Toolbar-->\r\n");
      out.write("        <div id=\"kt_app_toolbar\" class=\"app-toolbar py-3 py-lg-6\">\r\n");
      out.write("            <!--begin::Toolbar container-->\r\n");
      out.write("            <div id=\"kt_app_toolbar_container\" class=\"app-container container-fluid d-flex flex-stack\">\r\n");
      out.write("                <!--begin::Page title-->\r\n");
      out.write("                <div class=\"page-title d-flex flex-column justify-content-center flex-wrap me-3\">\r\n");
      out.write("                    <!--begin::Title-->\r\n");
      out.write("                    <h1 class=\"page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0\">\r\n");
      out.write("                        Multipurpose</h1>\r\n");
      out.write("                    <!--end::Title-->\r\n");
      out.write("                    <!--begin::Breadcrumb-->\r\n");
      out.write("                    <ul class=\"breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1\">\r\n");
      out.write("                        <!--begin::Item-->\r\n");
      out.write("                        <li class=\"breadcrumb-item text-muted\">\r\n");
      out.write("                            <a href=\"/\" class=\"text-muted text-hover-primary\">Home</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!--end::Item-->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!--end::Breadcrumb-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--end::Page title-->\r\n");
      out.write("                <!--begin::Actions-->\r\n");
      out.write("                <div class=\"d-flex align-items-center gap-2 gap-lg-3\">\r\n");
      out.write("                    <!--begin::Secondary button-->\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm fw-bold btn-secondary\" data-bs-toggle=\"modal\"\r\n");
      out.write("                       data-bs-target=\"#kt_modal_create_app\">Rollover</a>\r\n");
      out.write("                    <!--end::Secondary button-->\r\n");
      out.write("                    <!--begin::Primary button-->\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-sm fw-bold btn-primary\" data-bs-toggle=\"modal\"\r\n");
      out.write("                       data-bs-target=\"#kt_modal_new_target\">Add Target</a>\r\n");
      out.write("                    <!--end::Primary button-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--end::Actions-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--end::Toolbar container-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--end::Toolbar-->\r\n");
      out.write("        <!--begin::Content-->\r\n");
      out.write("        <div id=\"kt_app_content\" class=\"app-content flex-column-fluid\">\r\n");
      out.write("            <!--begin::Content container-->\r\n");
      out.write("            <div id=\"kt_app_content_container\" class=\"app-container container-fluid\">\r\n");
      out.write("                <!--begin::Row-->\r\n");
      out.write("                <div class=\"row g-5 gx-xl-10 mb-5 mb-xl-10\">\r\n");
      out.write("                    <!--begin::Col-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-6 col-xxl-12 mb-md-5 mb-xl-10\">\r\n");
      out.write("                        <!--begin::Row-->\r\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails.size() == 0 ? \"No product details!\" : \"\"}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                        <div class=\"row g-5 gx-xl-10 mb-5 mb-xl-10\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--end::Row-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--end::Col-->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--end::Row-->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--end::Content container-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--end::Content-->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--end::Content wrapper-->\r\n");
      out.write("</div>\r\n");
      out.write("<!--end::Main-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/product-details.jsp(66,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product-details.jsp(66,28) '${productDetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productDetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/product-details.jsp(66,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("productDetail");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <!--begin::Col-->\r\n");
            out.write("                                <div class=\"col-md-6 col-lg-6 col-xl-6 col-xxl-3 mb-md-5 mb-xl-10\">\r\n");
            out.write("                                    <!--begin::Product card-->\r\n");
            out.write("                                    <div class=\"card-xl-stretch me-md-6\">\r\n");
            out.write("                                        <!--begin::Overlay-->\r\n");
            out.write("                                        <span class=\"d-block overlay mb-4\"\r\n");
            out.write("                                              data-fslightbox=\"lightbox-hot-sales\">\r\n");
            out.write("                                            <!--begin::Image-->\r\n");
            out.write("                                            <div class=\"overlay-wrapper bgi-no-repeat bgi-position-center bgi-size-cover card-rounded min-h-175px\"\r\n");
            out.write("                                                 style=\"background-image:url('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.hinhAnh}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\"></div>\r\n");
            out.write("                                            <!--end::Image-->\r\n");
            out.write("                                            <!--begin::Action-->\r\n");
            out.write("                                            <div class=\"overlay-layer bg-dark card-rounded bg-opacity-25\">\r\n");
            out.write("                                                <i class=\"ki-duotone ki-eye fs-2x text-white\"></i>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <!--end::Action-->\r\n");
            out.write("                                        </span>\r\n");
            out.write("                                        <!--end::Overlay-->\r\n");
            out.write("                                        <!--begin::Body-->\r\n");
            out.write("                                        <div class=\"m-0\">\r\n");
            out.write("                                            <!--begin::Bestseller-->\r\n");
            out.write("                                            <span class=\"badge badge-success\">Bestseller</span>\r\n");
            out.write("                                            <!--end::Bestseller-->\r\n");
            out.write("                                            <!--begin::Title-->\r\n");
            out.write("                                            <span\r\n");
            out.write("                                                    class=\"fs-4 text-gray-900 fw-bold text-hover-primary text-gray-900 lh-base\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.sanPham.ten}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('-');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.ten}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                            <!--end::Title-->\r\n");
            out.write("                                            <!--begin::Author-->\r\n");
            out.write("                                            <div class=\"base text-gray-600 mt-2 mb-2\">\r\n");
            out.write("                                                Horizon Tech\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <!--end::Author-->\r\n");
            out.write("                                            <!--begin::Rating-->\r\n");
            out.write("                                            <div class=\"d-flex gap-2 mt-2 mb-2\">\r\n");
            out.write("                                                <!--begin::Average-->\r\n");
            out.write("                                                <div class=\"fw-bold base text-gray-900\">\r\n");
            out.write("                                                    5.0\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                                <!--end::Average-->\r\n");
            out.write("                                                <!--begin::Star-->\r\n");
            out.write("                                                <div class=\"rating\">\r\n");
            out.write("                                                    <div class=\"rating-label checked\">\r\n");
            out.write("                                                        <i class=\"ki-duotone ki-star base\"></i>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                    <div class=\"rating-label checked\">\r\n");
            out.write("                                                        <i class=\"ki-duotone ki-star base\"></i>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                    <div class=\"rating-label checked\">\r\n");
            out.write("                                                        <i class=\"ki-duotone ki-star base\"></i>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                    <div class=\"rating-label checked\">\r\n");
            out.write("                                                        <i class=\"ki-duotone ki-star base\"></i>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                    <div class=\"rating-label checked\">\r\n");
            out.write("                                                        <i class=\"ki-duotone ki-star base\"></i>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                                <!--end::Star-->\r\n");
            out.write("                                                <!--begin::Count-->\r\n");
            out.write("                                                <div class=\"base text-gray-600\">\r\n");
            out.write("                                                    (998)\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                                <!--end::Count-->\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <!--end::Rating-->\r\n");
            out.write("                                            <!--begin::Price-->\r\n");
            out.write("                                            <div class=\"fw-bold fs-4 text-gray-900 mt-2 mb-2\">\r\n");
            out.write("                                                ₫");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.donGia}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <!--end::Price-->\r\n");
            out.write("                                            <!--begin::Btn add to cart-->\r\n");
            out.write("                                            <a href=\"/add-to-cart?pid=1&pdid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetail.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-primary w-100\">Thêm vào giỏ hàng</a>\r\n");
            out.write("                                            <!--end::Btn add to cart-->\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                        <!--end::Body-->\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <!--end::Product card-->\r\n");
            out.write("                                </div>\r\n");
            out.write("                                <!--end::Col-->\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
